### ISSUE TITLE
Please add `Worker::len()` and `Stealer::len()` for getting the number of current items in the queue

### ISSUE THREAD

**Issue by Boscop** [asynchronics/st3#6]
Thanks for making this useful crate!

Can you please also add `Worker::len()` and `Stealer::len()` for getting the number of current items in the queue?
It would be very useful in my use case (as it would allow eliminating the overhead of keeping my own thread-local counter for each worker and manually incrementing/decrementing it).

Thanks :)

**Comment by sbarral** [comment]
Note that you can already obtain this by subtracting `Worker::spare_capacity()` from `Worker::capacity()`.

The `Worker::len()` method was in fact replaced by `Worker::spare_capacity()` in v0.3.0 as I couldn't really see some use for the former and was afraid it could be misused as it can overestimate the actual number of items in case of  concurrent stealing operation. But if you confirm that you are aware of this caveat and that it is still more useful to you than `spare_capacity` then no problem, I will reintroduce it.

The use-case for a `Stealer::len()` is even less clear to me, do you have one or is your suggestion mainly motivated by symmetry between the worker and stealer API? Again, I am not against introducing it, but I'd prefer to make sure that its potential usefulness outweighs the risks of it being misused.

**Comment by sbarral** [comment]
@Boscop Friendly bump :-)
(just to be clear in case it wasn't, my reply was not a refusal but a request for feedback so I can make an informed decision).

**Comment by sbarral** [comment]
Closing for now, feel free to reopen.
